name: spen_remote
description: "A Flutter plugin to integrate with the Samsung S Pen Remote SDK."
version: 0.0.2
homepage: https://github.com/2IIZ
repository: https://github.com/2IIZ/spen_remote

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.twiz.spen_remote
        pluginClass: SpenRemotePlugin
